import dynamical_aspects_symmetries_equivariant_bifurcation_foundation_canonical_lane_mathlib.GateLemmas
import dynamical_aspects_symmetries_equivariant_bifurcation_foundation_canonical_lane_mathlib.FinalTheorem
